### PR TITLE
Session workflow

### LINKED ISSUE #65: Session Workflow API, Node allocation
# Story

As a developer working on Duffy,
I want to know how the workflow to reserve nodes, use and release them is mapped to the API,
so I can implement it.

# Acceptance Criteria

- [x] A document exists which describes
  - [x] the API endpoints involved in the nodes reservation workflow
  - [x] and how a client will use them throughout the workflow
- [x] A Pydantic model exists which let's users submit 'specifications' of the type and amount of nodes they need in a session
- [x] The `session` endpoint
  - [x] accepts such specifications in `POST` requests, attempting to allocate matching nodes for the session from those active and unused, and returns suitable results, status codes, errors if allocation fails.
  - [x] lists allocated nodes in structures returned from the controller functions.
  - [x] accepts `PUT` requests which lets normal tenants only set `active` to `false`, i.e. retire a session which will kick off the undeployment of the nodes etc.

# Background

For the time being, this 👇 is the document mentioned above:

### Requesting nodes

API endpoints are implemented, and the central object node reservation revolves around is the 'session'. However, users shouldn't manipulate sessions and their related nodes individually, this work needs to be done by Duffy, users just need a way to tell Duffy what 'types' of nodes they need and how many (e.g. "2 bare metal, 1 large VM and 2 small VMs") when they request a session by `POST`-ing to `/api/v1/sessions`:

```
...
"nodes_specs": [
  {"quantity": 2, "type": "physical", "distro_type": "centos", "distro_version": "8"},
  {"quantity": 1, "type": "virtual", "flavour": "large", "distro_type": "fedora", "distro_version": "34"},
  {"quantity": 2, "type": "virtual", "flavour": "medium", "distro_type": "fedora", "distro_version": "34"},
],
...
```

### Retiring a session

We could abuse the `DELETE` HTTP method on a particular session, but this is misleasing as no objects are deleted. The most "RESTful" thing to do is (I guess) to let users modify set a sessions `active` value to `false`, e.g.:

```
http --json PUT http://localhost:8080/api/v1/sessions/1234 active:=false
...
```

## Listing allocated nodes

Currently, the structures returned from API endpoints are plain ORM objects. However, sessions and nodes are connected via intermediate `SessionNode` objects, which wraps a many-to-many intermediate table with additional fields. This needs to be suitably proxied into `Session` so a Pydantic model can serialize it to JSON like this:

```
"session": {
  "id": ...,
  "project": { ... },
  "nodes": [
    {"id": ..., "type": ..., "distro_type": ..., "distro_version": ...},
    ...
  ],
}
```

### LINKED ISSUE #158: Leaky DB sessions
@t0xic0der discovered an issue while reviewing #152: Namely that retiring a session didn't work through the API because a write lock held on the sqlite database file wasn't released. I examined the issue and found that a database session object from a previous (purposefully) failed request stuck around and wasn't cleaned up properly. To fix this, we need to refactor how DB sessions are handled to ensure we have one session per request which is cleaned up afterwards.

### PR DESCRIPTION
**Pull request by nphilipp**
This implements a good deal of #65: accepting specifications of requested nodes when creating sessions and returning the associated nodes with sessions from the API. It doesn't implement a controller for updating sessions (to let tenants set them inactive) yet, though.

Additionally, implement filling a DB with test data (as test fixtures and an extension to the `setup-db` command) and some refinement to tests.

# How to Test

- Delete the database (file) and perhaps recreate it (PostgreSQL)
- Setup the database and fill it with test data, e.g.:
```
(duffy) nils@makake:~/src/fedora-infra/duffy (dev--session-workflow)> duffy -c etc/duffy-psql-config.yaml setup-db --test-data
Creating database schema
Setting up database migrations
Creating test data
Caution! Created tenants with deterministic API keys:
	admin: ae6c10d0-0b13-554c-b976-a05d8a18f0cc
	tenant: a8b9899d-b128-59a1-aa86-754920b7f5ed
Don't use in production!
(duffy) nils@makake:~/src/fedora-infra/duffy (dev--session-workflow)>
```
- Verify the test data is there, e.g.:
```
(duffy) nils@makake:~/src/fedora-infra/duffy (dev--session-workflow)> psql duffy
psql (13.4)
Type "help" for help.

duffy=> select * from nodes;
          created_at           | retired_at | id |    type    |               hostname                
|    ipaddr    | state  | comment | distro_type | distro_version 
-------------------------------+------------+----+------------+---------------------------------------
+--------------+--------+---------+-------------+----------------
 2021-12-21 12:18:22.036233+01 |            |  1 | opennebula | node-opennebula-small-7.example.net   
| 192.168.1.17 | active |         | fedora      | 35
[ ... ]
 2021-12-21 12:18:22.036233+01 |            | 72 | opennebula | node-opennebula-medium-2.example.net  
| 192.168.2.12 | active |         | centos      | 8Stream
(72 rows)

duffy=>
```
- Start the app server
```
(duffy) nils@makake:~/src/fedora-infra/duffy (dev--session-workflow)> duffy -c etc/duffy-psql-config.yaml serve
 * Starting Duffy...
 * Host address : 127.0.0.1
 * Port number  : 8080
 * Log level    : warning
 * Serving API docs on http://127.0.0.1:8080/docs
```
- Request a session with a certain set of nodes:
```
(duffy) nils@makake:~/src/fedora-infra/duffy (dev--session-workflow)> http --json post http://localhost:8080/api/v1/sessions tenant_id=2 nodes_specs:='[{"quantity": 1, "type": "physical", "distro_type": "fedora", "distro_version": "35"}, {"quantity": 2, "type": "virtual", "flavour": "medium", "distro_type": "fedora", "distro_version": "35"}]'
HTTP/1.1 201 Created
content-length: 769
content-type: application/json
date: Tue, 21 Dec 2021 12:22:12 GMT
server: uvicorn

{
    "action": "post",
    "session": {
        "active": true,
        "created_at": "2021-12-21T11:22:13.362065+00:00",
        "id": 1,
        "nodes": [
            {
                "comment": null,
                "distro_type": "fedora",
                "distro_version": "35",
                "hostname": "node-seamicro-2.example.net",
                "ipaddr": "192.168.0.12",
                "type": "seamicro"
            },
            {
                "comment": null,
                "distro_type": "fedora",
                "distro_version": "35",
                "flavour": "medium",
                "hostname": "node-opennebula-medium-3.example.net",
                "ipaddr": "192.168.2.13",
                "type": "opennebula"
            },
            {
                "comment": null,
                "distro_type": "fedora",
                "distro_version": "35",
                "flavour": "medium",
                "hostname": "node-opennebula-medium-5.example.net",
                "ipaddr": "192.168.2.15",
                "type": "opennebula"
            }
        ],
        "retired_at": null,
        "tenant": {
            "active": true,
            "created_at": "2021-12-21T11:18:22.036233+00:00",
            "id": 2,
            "is_admin": false,
            "name": "tenant",
            "retired_at": null,
            "ssh_key": "Boo!"
        }
    }
}
```
- Request it again to verify that Duffy refuses to hand out more nodes than are available:
```
(duffy) nils@makake:~/src/fedora-infra/duffy (dev--session-workflow)> http --json post http://localhost:8080/api/v1/sessions tenant_id=2 nodes_specs:='[{"quantity": 1, "type": "physical", "distro_type": "fedora", "distro_version": "35"}, {"quantity": 2, "type": "virtual", "flavour": "medium", "distro_type": "fedora", "distro_version": "35"}]'
HTTP/1.1 422 Unprocessable Entity
content-length: 122
content-type: application/json
date: Tue, 21 Dec 2021 12:23:16 GMT
server: uvicorn

{
    "detail": "can't reserve nodes: type=<NodeType.physical: 'physical'> quantity=1 distro_type='fedora' distro_version='35'"
}
```
- Release the reserved nodes by setting the `active` flag to `false` (check `active` and `retired_at` in the response):
```
(duffy) nils@makake:~/src/fedora-infra/duffy (dev--session-workflow)> http --json put http://localhost:8080/api/v1/sessions/1 active:=false
HTTP/1.1 200 OK
content-length: 799
content-type: application/json
date: Tue, 21 Dec 2021 12:25:33 GMT
server: uvicorn

{
    "action": "put",
    "session": {
        "active": false,
        "created_at": "2021-12-21T11:22:13.362065+00:00",
        "id": 1,
        "nodes": [
            {
                "comment": null,
                "distro_type": "fedora",
                "distro_version": "35",
                "hostname": "node-seamicro-2.example.net",
                "ipaddr": "192.168.0.12",
                "type": "seamicro"
            },
            {
                "comment": null,
                "distro_type": "fedora",
                "distro_version": "35",
                "flavour": "medium",
                "hostname": "node-opennebula-medium-3.example.net",
                "ipaddr": "192.168.2.13",
                "type": "opennebula"
            },
            {
                "comment": null,
                "distro_type": "fedora",
                "distro_version": "35",
                "flavour": "medium",
                "hostname": "node-opennebula-medium-5.example.net",
                "ipaddr": "192.168.2.15",
                "type": "opennebula"
            }
        ],
        "retired_at": "2021-12-21T12:25:33.928737+00:00",
        "tenant": {
            "active": true,
            "created_at": "2021-12-21T11:18:22.036233+00:00",
            "id": 2,
            "is_admin": false,
            "name": "tenant",
            "retired_at": null,
            "ssh_key": "Boo!"
        }
    }
}
```

### CODE REVIEW

**Review by gridhead — COMMENTED** [review]
So this is what I did.

1. `$ git checkout dev--session-workflow`
1. `$ git pull nils dev--session-workflow`
1. `$ source venv/bin/activate`
1. `(venv) $ poetry install`
1. `(venv) $ pytest`
	`224 passed, 90 skipped, 49 warnings in 32.85s`
	Nice.
1. `(venv) $ duffy -c etc/duffy-config.yaml setup-db --test-data`
	```
	Creating database schema
	Setting up database migrations
	Creating test data
	Caution! Created tenants with deterministic API keys:
		admin: ae6c10d0-0b13-554c-b976-a05d8a18f0cc
		tenant: a8b9899d-b128-59a1-aa86-754920b7f5ed
	Don't use in production!
	```
1. `(venv) $ sqlite3 database.db`
1. `sqlite3 > .tables`
	```
	alembic_version  opennebulanodes  sessions         virtualnodes   
	chassis          physicalnodes    sessions_nodes 
	nodes            seamicronodes    tenants  
	```
1. `sqlite3 > select count(*) from nodes;`
	```
	72
	```
1. `[Ctrl+D]`
1. `(venv) $ duffy -c etc/duffy-config.yaml -l debug serve`
1. `(venv) $ http --json post http://localhost:8080/api/v1/sessions tenant_id=2 nodes_specs:='[{"quantity": 1, "type": "physical", "distro_type": "fedora", "distro_version": "35"}, {"quantity": 2, "type": "virtual", "flavour": "medium", "distro_type": "fedora", "distro_version": "35"}]'`
	It worked as promised.
1. `(venv) $ http --json post http://localhost:8080/api/v1/sessions tenant_id=2 nodes_specs:='[{"quantity": 1, "type": "physical", "distro_type": "fedora", "distro_version": "35"}, {"quantity": 2, "type": "virtual", "flavour": "medium", "distro_type": "fedora", "distro_version": "35"}]'`
	It worked as promised.
1. `(venv) $ http --json put http://localhost:8080/api/v1/sessions/1 active:=false`
	It didn't work as promised.
	```
	HTTP/1.1 500 Internal Server Error
	content-length: 21
	content-type: text/plain; charset=utf-8
	date: Wed, 22 Dec 2021 04:17:17 GMT
	server: uvicorn

	Internal Server Error

	```
	Here's a traceback from the server logs, focused to the parts where the error took place.
	```
	INFO:     127.0.0.1:44350 - "PUT /api/v1/sessions/1 HTTP/1.1" 500 Internal Server Error
	ERROR:    Exception in ASGI application
	Traceback (most recent call last):
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1782, in _execute_context
		self.dialect.do_executemany(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/default.py", line 729, in do_executemany
		cursor.executemany(statement, parameters)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 111, in executemany
		self._adapt_connection._handle_exception(error)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 229, in _handle_exception
		raise error
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 105, in executemany
		self.await_(_cursor.executemany(operation, seq_of_parameters))
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
		return current.driver.switch(awaitable)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
		value = await result
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/cursor.py", line 44, in executemany
		await self._execute(self._cursor.executemany, sql, parameters)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
		return await self._conn._execute(fn, *args, **kwargs)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
		return await future
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/core.py", line 102, in run
		result = function()
	sqlite3.OperationalError: database is locked

	The above exception was the direct cause of the following exception:

	Traceback (most recent call last):
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
		result = await app(self.scope, self.receive, self.send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
		return await self.app(scope, receive, send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/fastapi/applications.py", line 208, in __call__
		await super().__call__(scope, receive, send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/applications.py", line 112, in __call__
		await self.middleware_stack(scope, receive, send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
		raise exc
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
		await self.app(scope, receive, _send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
		raise exc
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
		await self.app(scope, receive, sender)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/routing.py", line 656, in __call__
		await route.handle(scope, receive, send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/routing.py", line 259, in handle
		await self.app(scope, receive, send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/routing.py", line 61, in app
		response = await func(request)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/fastapi/routing.py", line 226, in app
		raw_response = await run_endpoint_function(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
		return await dependant.call(**values)
	  File "/home/t0xic0der/Projects/duffy/duffy/app/controllers/session.py", line 156, in update_session
		await DBSession.commit()
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 576, in commit
		return await greenlet_spawn(self.sync_session.commit)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 136, in greenlet_spawn
		result = context.switch(value)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
		self._transaction.commit(_to_root=self.future)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit
		self._prepare_impl()
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
		self.session.flush()
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 3348, in flush
		self._flush(objects)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 3487, in _flush
		with util.safe_reraise():
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
		compat.raise_(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
		raise exception
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 3448, in _flush
		flush_context.execute()
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
		rec.execute(self)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
		util.preloaded.orm_persistence.save_obj(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
		_emit_update_statements(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1000, in _emit_update_statements
		c = connection._execute_20(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
		return meth(self, args_10style, kwargs_10style, execution_options)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
		return connection._execute_clauseelement(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
		ret = self._execute_context(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
		self._handle_dbapi_exception(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
		util.raise_(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
		raise exception
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1782, in _execute_context
		self.dialect.do_executemany(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/default.py", line 729, in do_executemany
		cursor.executemany(statement, parameters)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 111, in executemany
		self._adapt_connection._handle_exception(error)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 229, in _handle_exception
		raise error
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 105, in executemany
		self.await_(_cursor.executemany(operation, seq_of_parameters))
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
		return current.driver.switch(awaitable)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
		value = await result
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/cursor.py", line 44, in executemany
		await self._execute(self._cursor.executemany, sql, parameters)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
		return await self._conn._execute(fn, *args, **kwargs)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
		return await future
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/core.py", line 102, in run
		result = function()
	sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
	[SQL: UPDATE nodes SET state=? WHERE nodes.id = ?]
	[parameters: (('deprovisioning', 1), ('deprovisioning', 9), ('deprovisioning', 32))]
	(Background on this error at: https://sqlalche.me/e/14/e3q8)
	ERROR:uvicorn.error:Exception in ASGI application
	Traceback (most recent call last):
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1782, in _execute_context
		self.dialect.do_executemany(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/default.py", line 729, in do_executemany
		cursor.executemany(statement, parameters)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 111, in executemany
		self._adapt_connection._handle_exception(error)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 229, in _handle_exception
		raise error
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 105, in executemany
		self.await_(_cursor.executemany(operation, seq_of_parameters))
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
		return current.driver.switch(awaitable)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
		value = await result
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/cursor.py", line 44, in executemany
		await self._execute(self._cursor.executemany, sql, parameters)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
		return await self._conn._execute(fn, *args, **kwargs)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
		return await future
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/core.py", line 102, in run
		result = function()
	sqlite3.OperationalError: database is locked

	The above exception was the direct cause of the following exception:

	Traceback (most recent call last):
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
		result = await app(self.scope, self.receive, self.send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
		return await self.app(scope, receive, send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/fastapi/applications.py", line 208, in __call__
		await super().__call__(scope, receive, send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/applications.py", line 112, in __call__
		await self.middleware_stack(scope, receive, send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
		raise exc
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
		await self.app(scope, receive, _send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
		raise exc
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
		await self.app(scope, receive, sender)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/routing.py", line 656, in __call__
		await route.handle(scope, receive, send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/routing.py", line 259, in handle
		await self.app(scope, receive, send)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/starlette/routing.py", line 61, in app
		response = await func(request)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/fastapi/routing.py", line 226, in app
		raw_response = await run_endpoint_function(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
		return await dependant.call(**values)
	  File "/home/t0xic0der/Projects/duffy/duffy/app/controllers/session.py", line 156, in update_session
		await DBSession.commit()
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 576, in commit
		return await greenlet_spawn(self.sync_session.commit)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 136, in greenlet_spawn
		result = context.switch(value)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
		self._transaction.commit(_to_root=self.future)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit
		self._prepare_impl()
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
		self.session.flush()
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 3348, in flush
		self._flush(objects)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 3487, in _flush
		with util.safe_reraise():
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
		compat.raise_(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
		raise exception
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 3448, in _flush
		flush_context.execute()
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
		rec.execute(self)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
		util.preloaded.orm_persistence.save_obj(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
		_emit_update_statements(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1000, in _emit_update_statements
		c = connection._execute_20(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
		return meth(self, args_10style, kwargs_10style, execution_options)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
		return connection._execute_clauseelement(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
		ret = self._execute_context(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
		self._handle_dbapi_exception(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
		util.raise_(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
		raise exception
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1782, in _execute_context
		self.dialect.do_executemany(
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/engine/default.py", line 729, in do_executemany
		cursor.executemany(statement, parameters)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 111, in executemany
		self._adapt_connection._handle_exception(error)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 229, in _handle_exception
		raise error
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 105, in executemany
		self.await_(_cursor.executemany(operation, seq_of_parameters))
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
		return current.driver.switch(awaitable)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
		value = await result
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/cursor.py", line 44, in executemany
		await self._execute(self._cursor.executemany, sql, parameters)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
		return await self._conn._execute(fn, *args, **kwargs)
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
		return await future
	  File "/home/t0xic0der/Projects/duffy/venv/lib64/python3.10/site-packages/aiosqlite/core.py", line 102, in run
		result = function()
	sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
	[SQL: UPDATE nodes SET state=? WHERE nodes.id = ?]
	[parameters: (('deprovisioning', 1), ('deprovisioning', 9), ('deprovisioning', 32))]
	(Background on this error at: https://sqlalche.me/e/14/e3q8)

	```
	I suspect that wouldn't work with SQLite3 database and hence, you suggested PostgreSQL database in your instructions.

**Comment by nphilipp** [comment]
Hmm, I suspect the reason for this is some unfinished transaction. I'll have to debug this.

**Comment by nphilipp** [comment]
The latest push should fix the leaky DB sessions issue (#158).

**Comment by nphilipp** [comment]
…and now the tests work even on Python 3.8. :joy:

**Review by gridhead — APPROVED** [review]
Gave it a spin again. LGTM.

**Pull request merged**
