### PR TITLE
Simplify nodes and configuration fixes

### LINKED ISSUE #208: Simplify nodes
# Story

As a developer of Duffy,
I only want to care about information necessary to run Duffy,
so that I'm not distracted and the code doesn't get too complex.

# Acceptance Criteria

In the Node DB model class …
- [x] … a `pool` field is added to store the name of the node pool to which a node is assigned.
- [x] … a `data` (JSON) field is added which allows storing arbitrary auxiliary data, e.g. results from provisioning which allow a node to be deprovisioned.
- [x] … the fields for OS type & version, architecture are removed.

### LINKED ISSUE #209: Validate configuration
# Story

As a Duffy developer,
I want that the configuration file structure is validated when it's loaded,
so I don't have to put structural checks all over the place.

# Acceptance Criteria

- [x] Pydantic models exist which describe how a valid configuration file looks like.
- [x] When loading configuration files, their structure is validated using these models.

### PR DESCRIPTION
**Pull request by nphilipp**
This simplifies nodes (as discussed, getting rid of OS type, version, arch in favour of a `data` JSON field) and fixes some issues with configuration: merging from multiple sources was broken (mainly needed in tests) and I found myself doing too much error handling regarding configuration structure scattered all across the code, so I bit the bullet and added validation of the configuration structure using Pydantic. Additionally, it moves settings for the app into its own sub-block `app`, this lets us run both the v1 API and legacy apps on the same host using the same config file.

### CODE REVIEW

**Comment by nphilipp** [comment]
The latest push moves app settings into their own subblock `app`.

**Review by gridhead — APPROVED** [review]
Pytest isn't mad and it looks OK to me on glancing. :)

**Comment by gridhead** [comment]
P.S. I did more than glancing even though I stated that for I used this code as a base for my #184 so I do know what's going on here.

**Comment by nphilipp** [comment]
:smile:

**Pull request merged**
