### PR TITLE
Node pools & Ansible backend (provisioning)

### LINKED ISSUE #134: Node Pools
# Story

As someone using Duffy,
I want it to maintain pools of nodes,
so they can be quickly handed out when requests come in.

# Acceptance Criteria

- [x] A method exists to define pools in configuration
- [x] Duffy can determine which pool an active nodes belongs to
- [x] Duffy can tell how many nodes are available per pool to be handed out

# Background, Thoughts

It could very well be that we can get by without storing e.g. OS type, version, (VM) flavour individually and use a simple string tag on nodes to describe the pool that a machine belongs to, and tenants would only ask for x machines of a node with a certain label. Because of the long-lived bare metal nodes, we need to add a field in nodes to store their architecture.

### LINKED ISSUE #180: Generic (de)provisioning of nodes
# Story

As a Duffy developer,
I want a generic API to provision and deprovision nodes,
so that I don't have to care about different types of nodes in other more generic areas of the code.

# Acceptance Criteria

- [x] A Python API of some sort exists which offers methods to
  - [x] provision nodes of a certain type (e.g. bare metal vs. virtual) and profile (e.g. OS type, version, architecture)
  - [x] deprovision existing nodes

# Background

This is a building block for #163 and #164 and mostly about the definition of the API, possibly as an abstract base class from which concrete classes can be derived. The provisioning method has to be able to fail (callers should expect that and react accordingly, most likely by ignoring it and re-request nodes in a future round).

### PR DESCRIPTION
**Pull request by nphilipp**
This is supposed to fix the provisioning side #134, #180, see the deprovisioning bit in #220. Yay for bite-sized pieces of work!

### CODE REVIEW

**Comment by gridhead** [comment]
Here's what I do.

1. `pytest`
2. `ERROR  - ModuleNotFoundError: No module named 'ansible_runner'`
3. `poetry install`
4. `ansible_runner` does NOT get installed - we would want to add it in the `pyproject.toml`
5. `pip3 install ansible_runner`
6. `pytest`
7. `301 passed, 120 skipped, 63 warnings in 77.65s (0:01:17)`
8. Nice.

**Comment by gridhead** [comment]
I would take a deeper look at the code when @nphilipp shares the testing steps but I suppose that @siddharthvipul would be able to make a lot more sense of the way the backend works, much more than I can.

**Comment by nphilipp** [comment]
The latest push rebases on top of your recently merged PR and fixes conflicts plus the missing dependencies, i.e. not only adds them as an optional extra but also as plain dev dependencies (except `pyone` which is a backend-specific dependency, we only need it for deployments that talk to a real OpenNebula cluster).

**Comment by nphilipp** [comment]
The latest push adds new testcases which actually run the `tests/task/playbooks/provision.yml` playbook which also documents how Duffy runs these playbooks, what gets passed into it and how results are passed back.

**Comment by gridhead** [comment]
I purged the local copy of your branch, fetched the most recently made changes, checked out your branch again and ran `pytest`.

**Comment by gridhead** [comment]
Apologies for mistakenly closing the PR. Butter fingers, I guess. `pytest` ran just fine and all tests passed.

**Review by gridhead — APPROVED** [review]
LGTM.

**Pull request merged**
