### PR TITLE
Add endpoint authentication

### PR DESCRIPTION
**Pull request by gridhead**
Signed-off-by: Akashdeep Dhar <akashdeep.dhar@gmail.com>

### CODE REVIEW

**Comment by gridhead** [comment]
How do you play around with this draft PR?

1. `$ git checkout authenticate-endpoint-access`
2. `$ source venv/bin/activate`
3. `(venv) $ poetry install`
4. `(venv) $ duffy -c etc/duffy-config.yaml -l debug serve`
5. See the tests fail here `(venv) $ pytest`
6. Open up http://localhost:8080/docs/ in a browser
7. Click on the `Authorize` button
8. In the modal, type in the (Tenant) `name` in the username field and the (Tenant) `api_key` in the password field for an admin tenant 
9. Press `Authorize` button in the modal
10. Do stuff with the endpoints

The Oauth bearer makes use of the `name` of the tenant to authorize requests which is not very secure. Me and @siddharthvipul sat on a call and we thought that we are better off using the `api_key` to both, uniquely identify as well as authenticate the tenants. For that, we'd have to ensure that the UUIDs are auto-generated by the server code and are unique.

**Comment by nphilipp** [comment]
Hi Akash,

as discussed, I played around with HTTP basic authentication on top of my PR #152 and came up with this (plus example use in the session controller, minus tests :wink:) – which drops the authenticated tenant right into the controller function:

````
diff --git a/duffy/api_models/session.py b/duffy/api_models/session.py
index 745a162..090ecac 100644
--- a/duffy/api_models/session.py
+++ b/duffy/api_models/session.py
@@ -1,5 +1,5 @@
 from abc import ABC
-from typing import List, Literal, Union
+from typing import List, Literal, Optional, Union
 
 from pydantic import BaseModel, conint
 
@@ -59,7 +59,7 @@ class SessionBase(BaseModel, ABC):
 
 
 class SessionCreateModel(SessionBase):
-    tenant_id: int
+    tenant_id: Optional[int]
     nodes_specs: List[Union[PhysicalNodesSpec, VirtualNodesSpec]]
 
 
diff --git a/duffy/app/auth.py b/duffy/app/auth.py
new file mode 100644
index 0000000..297159d
--- /dev/null
+++ b/duffy/app/auth.py
@@ -0,0 +1,37 @@
+from fastapi import HTTPException, Security
+from fastapi.security import HTTPBasic, HTTPBasicCredentials
+from sqlalchemy import select
+from starlette.status import HTTP_401_UNAUTHORIZED, HTTP_403_FORBIDDEN
+
+from ..database import DBSession
+from ..database.model import Tenant
+
+
+def get_current_tenant(optional: bool = False, **kwargs):
+    if optional:
+        kwargs["auto_error"] = False
+    security = HTTPBasic(realm="duffy", **kwargs)
+
+    async def wrapped_get_current_tenant(credentials: HTTPBasicCredentials = Security(security)):
+        if not credentials:
+            if not optional:
+                raise HTTPException(HTTP_403_FORBIDDEN)
+            else:
+                return None
+
+        tenant_name = credentials.username
+        api_key = credentials.password
+
+        tenant = (
+            await DBSession.execute(select(Tenant).filter_by(name=tenant_name))
+        ).scalar_one_or_none()
+
+        if not tenant or not tenant.validate_api_key(api_key):
+            raise HTTPException(HTTP_401_UNAUTHORIZED)
+
+        if not tenant.active:
+            raise HTTPException(HTTP_403_FORBIDDEN)
+
+        return tenant
+
+    return wrapped_get_current_tenant
diff --git a/duffy/app/controllers/session.py b/duffy/app/controllers/session.py
index 025384f..1ba0ddf 100644
--- a/duffy/app/controllers/session.py
+++ b/duffy/app/controllers/session.py
@@ -2,11 +2,16 @@
 This is the session controller.
 """
 
-from fastapi import APIRouter, HTTPException
+from fastapi import APIRouter, Depends, HTTPException
 from sqlalchemy import select
 from sqlalchemy.exc import IntegrityError
 from sqlalchemy.orm import selectinload
-from starlette.status import HTTP_201_CREATED, HTTP_404_NOT_FOUND, HTTP_422_UNPROCESSABLE_ENTITY
+from starlette.status import (
+    HTTP_201_CREATED,
+    HTTP_403_FORBIDDEN,
+    HTTP_404_NOT_FOUND,
+    HTTP_422_UNPROCESSABLE_ENTITY,
+)
 
 from ...api_models import (
     PhysicalNodesSpec,
@@ -18,13 +23,14 @@ from ...api_models import (
 from ...database import DBSession
 from ...database.model import PhysicalNode, Session, SessionNode, Tenant, VirtualNode
 from ...database.types import NodeState
+from ..auth import get_current_tenant
 
 router = APIRouter(prefix="/sessions")
 
 
 # http get http://localhost:8080/api/v1/sessions
 @router.get("", response_model=SessionResultCollection, tags=["sessions"])
-async def get_all_sessions():
+async def get_all_sessions(tenant: Tenant = Depends(get_current_tenant())):
     """
     Returns all sessions
     """
@@ -32,13 +38,15 @@ async def get_all_sessions():
         selectinload(Session.tenant),
         selectinload(Session.session_nodes).selectinload(SessionNode.node),
     )
+    if not tenant.is_admin:
+        query = query.filter_by(tenant=tenant)
     results = await DBSession.execute(query)
     return {"action": "get", "sessions": results.scalars().all()}
 
 
 # http get http://localhost:8080/api/v1/sessions/2
 @router.get("/{id}", response_model=SessionResult, tags=["sessions"])
-async def get_session(id: int):
+async def get_session(id: int, tenant: Tenant = Depends(get_current_tenant())):
     """
     Returns a session with the specified **ID**
     """
@@ -54,25 +62,33 @@ async def get_session(id: int):
     ).scalar_one_or_none()
     if not session:
         raise HTTPException(HTTP_404_NOT_FOUND)
+    if not tenant.is_admin and session.tenant != tenant:
+        raise HTTPException(HTTP_403_FORBIDDEN)
     return {"action": "get", "session": session}
 
 
 # http --json post http://localhost:8080/api/v1/sessions tenant_id=2
 @router.post("", status_code=HTTP_201_CREATED, response_model=SessionResult, tags=["sessions"])
-async def create_session(data: SessionCreateModel):
+async def create_session(data: SessionCreateModel, tenant: Tenant = Depends(get_current_tenant())):
     """
     Creates a session with the specified **tenant ID**
     """
-    tenant = (
-        await DBSession.execute(select(Tenant).filter_by(id=data.tenant_id))
-    ).scalar_one_or_none()
+    if tenant.is_admin and data.tenant_id is not None:
+        tenant = (
+            await DBSession.execute(select(Tenant).filter_by(id=data.tenant_id))
+        ).scalar_one_or_none()
+
+        if not tenant:
+            raise HTTPException(
+                HTTP_422_UNPROCESSABLE_ENTITY, f"can't find tenant with id {data.tenant_id}"
+            )
 
-    if not tenant:
-        raise HTTPException(
-            HTTP_422_UNPROCESSABLE_ENTITY, f"can't find tenant with id {data.tenant_id}"
-        )
-    if not tenant.active:
-        raise HTTPException(HTTP_422_UNPROCESSABLE_ENTITY, f"tenant '{tenant.name}' isn't active")
+        if not tenant.active:
+            raise HTTPException(
+                HTTP_422_UNPROCESSABLE_ENTITY, f"tenant '{tenant.name}' isn't active"
+            )
+    elif not tenant.is_admin and data.tenant_id is not None and data.tenant_id != tenant.id:
+        raise HTTPException(HTTP_403_FORBIDDEN, "can't create session for other tenant")
 
     session = Session(tenant=tenant)
     DBSession.add(session)
@@ -129,7 +145,9 @@ async def create_session(data: SessionCreateModel):
 
 # http --json put http://localhost:8080/api/v1/sessions/2 active:=false
 @router.put("/{id}", response_model=SessionResult, tags=["sessions"])
-async def update_session(id: int, data: SessionUpdateModel):
+async def update_session(
+    id: int, data: SessionUpdateModel, tenant: Tenant = Depends(get_current_tenant())
+):
     session = (
         await DBSession.execute(
             select(Session)
@@ -144,6 +162,9 @@ async def update_session(id: int, data: SessionUpdateModel):
     if not session:
         raise HTTPException(HTTP_404_NOT_FOUND)
 
+    if not tenant.is_admin or session.tenant != tenant:
+        raise HTTPException(HTTP_403_FORBIDDEN)
+
     if not session.active:
         raise HTTPException(HTTP_422_UNPROCESSABLE_ENTITY, f"session {id} is retired")
 
@@ -160,10 +181,12 @@ async def update_session(id: int, data: SessionUpdateModel):
 
 # http delete http://localhost:8080/api/v1/sessions/2
 @router.delete("/{id}", response_model=SessionResult, tags=["sessions"])
-async def delete_session(id: int):
+async def delete_session(id: int, tenant: Tenant = Depends(get_current_tenant())):
     """
     Deletes the session with the specified **ID**
     """
+    if not tenant.is_admin:
+        raise HTTPException(HTTP_403_FORBIDDEN)
     session = (
         await DBSession.execute(
             select(Session)
````

**Comment by gridhead** [comment]
Now that the authentication mech makes use of a combination of both tenant name and password, there's a change in the way this pull request should be tested.

## Phase 1 - Setting up admin tenant and client tenant accounts

1. `$ git checkout authenticate-endpoint-access`
2. `$ git pull t0xic0der authenticate-endpoint-access`
3. `$ source venv/bin/activate`
4. `(venv) $ poetry install`
5. `(venv) $ duffy -c etc/duffy-config.yaml shell`
6. `[duffy-shell]` `>>> from uuid import uuid4`
7. `[duffy-shell]` `>>> k1, k2 = uuid4(), uuid4()`
8. `[duffy-shell]` `>>> k1, k2`
	Make a note of the output - Example output follows
	`[duffy-shell]` `(UUID('05e8ac23-f652-4a60-adbe-d0c8ead9ace2'), UUID('c642357f-bde1-49bd-aaac-c76e20d402ca'))`
9. `[duffy-shell]` `>>> t1 = Tenant(name="alarm", is_admin=True, api_key=k1, ssh_key="hmmmmmmmmmmmmm")`
10. `[duffy-shell` `>>> t2 = Tenant(name="clock", is_admin=False, api_key=k2, ssh_key="mmmmmmmmmmmmmh")`
11. `[duffy-shell]` `>>> with SyncDBSession.begin():`
	`[duffy-shell]` `... 	SyncDBSession.add(t1)`
	`[duffy-shell]` `... 	SyncDBSession.add(t2)`
12. `[duffy-shell]` `>>> SyncDBSession.commit()`
13. `[duffy-shell]` `>>> from base64 import b64encode`
14. `[duffy-shell]` `>>> from json import dumps`
15. `[duffy-shell]` `>>> t1adcred = dumps({"username": "alarm", "password": str(k1)})`
16. `[duffy-shell]` `>>> t2adcred = dumps({"username": "clock", "password": str(k2)})`
17. `[duffy-shell]` `>>> t1adauth = b64encode(t1adcred.encode("ascii")).decode("ascii")`
18. `[duffy-shell]` `>>> t2adauth = b64encode(t2adcred.encode("ascii")).decode("ascii")`
19. `[duffy-shell]` `>>> t1adauth`
	Make a note of the output - Example output follows
	`[duffy-shell]` `'eyJ1c2VybmFtZSI6ICJhbGFybSIsICJwYXNzd29yZCI6ICIwNWU4YWMyMy1mNjUyLTRhNjAtYWRiZS1kMGM4ZWFkOWFjZTIifQ=='`
20. `[duffy-shell]` `>>> t2adauth`
	Make a note of the output - Example output follows
	`[duffy-shell]` `'eyJ1c2VybmFtZSI6ICJjbG9jayIsICJwYXNzd29yZCI6ICJjNjQyMzU3Zi1iZGUxLTQ5YmQtYWFhYy1jNzZlMjBkNDAyY2EifQ=='`

**Comment by gridhead** [comment]
After setting up the accounts for the admin tenants and client tenants, we'll check how they access the endpoints.

## Phase 2 - Testing the admin tenant accesses
1. `(venv) $ duffy -c etc/duffy-config.yaml -l debug serve`
2. Test the nodes endpoint `/api/v1/nodes`
	1. Test getting all nodes `[GET]` `/api/v1/nodes`
		```
		$ curl -X 'GET' \
		  'http://localhost:8080/api/v1/nodes' \
		  -H 'accept: application/json' \
		  -H 'Authorization: Bearer eyJ1c2VybmFtZSI6ICJhbGFybSIsICJwYXNzd29yZCI6ICIwNWU4YWMyMy1mNjUyLTRhNjAtYWRiZS1kMGM4ZWFkOWFjZTIifQ=='
		```
		Success, if you get something like the following
		```
		{
		  "action": "get",
		  "nodes": []
		}
		```
		Failure, if you get something different
	2. Test creating a node `[POST]` `/api/v1/nodes`
		```
		$ curl -X 'POST' \
		  'http://localhost:8080/api/v1/nodes' \
		  -H 'accept: application/json' \
		  -H 'Authorization: Bearer eyJ1c2VybmFtZSI6ICJhbGFybSIsICJwYXNzd29yZCI6ICIwNWU4YWMyMy1mNjUyLTRhNjAtYWRiZS1kMGM4ZWFkOWFjZTIifQ==' \
		  -H 'Content-Type: application/json' \
		  -d '{
		  "type": "opennebula",
		  "hostname": "str1ng",
		  "ipaddr": "192.168.0.1",
		  "comment": "string",
		  "flavour": "small"
		}'
		```
		Success, if you get something like the following
		```
		{
		  "action": "post",
		  "node": {
			"retired_at": null,
			"active": true,
			"created_at": "2021-12-21T05:14:27+00:00",
			"type": "opennebula",
			"hostname": "str1ng",
			"ipaddr": "192.168.0.1",
			"comment": "string",
			"id": 1,
			"state": "ready",
			"flavour": "small"
		  }
		}
		```
		Failure, if you get something different
	3. Testing retrieving a node `[GET]` `/api/v1/nodes/1`
		```
		$ curl -X 'GET' \
		  'http://localhost:8080/api/v1/nodes/1' \
		  -H 'accept: application/json' \
		  -H 'Authorization: Bearer eyJ1c2VybmFtZSI6ICJhbGFybSIsICJwYXNzd29yZCI6ICIwNWU4YWMyMy1mNjUyLTRhNjAtYWRiZS1kMGM4ZWFkOWFjZTIifQ=='
		```
		Success, if you get something like the following
		```
		{
		  "action": "get",
		  "node": {
			"retired_at": null,
			"active": true,
			"created_at": "2021-12-21T05:14:27+00:00",
			"type": "opennebula",
			"hostname": "str1ng",
			"ipaddr": "192.168.0.1",
			"comment": "string",
			"id": 1,
			"state": "ready",
			"flavour": "small"
		  }
		}
		```
		Failure, if you get something different
	4. Testing deleting a node `[DELETE` `/api/v1/nodes/1`
		```
		$ curl -X 'DELETE' \
		  'http://localhost:8080/api/v1/nodes/1' \
		  -H 'accept: application/json' \
		  -H 'Authorization: Bearer eyJ1c2VybmFtZSI6ICJhbGFybSIsICJwYXNzd29yZCI6ICIwNWU4YWMyMy1mNjUyLTRhNjAtYWRiZS1kMGM4ZWFkOWFjZTIifQ=='
		```
		Success, if you get something like the following
		```
		{
		  "action": "delete",
		  "node": {
			"retired_at": null,
			"active": true,
			"created_at": "2021-12-21T05:47:46+00:00",
			"type": "opennebula",
			"hostname": "str1ng",
			"ipaddr": "192.168.0.1",
			"comment": "string",
			"id": 1,
			"state": "ready",
			"flavour": "small"
		  }
		}
		```
		Failure, if you get something different
3. Similarly, test the sessions endpoint, tenants endpoint and chassis endpoint.

**Comment by gridhead** [comment]
After setting up the accounts for the admin tenants and client tenants, we'll check how they access the endpoints.

## Phase 3 - Testing the client tenant accesses
1. `(venv) $ duffy -c etc/duffy-config.yaml -l debug serve` (if the server is not running already)
2. Test the nodes endpoint `/api/v1/nodes`
	1. Test getting all nodes `[GET]` `/api/v1/nodes`
		```
		$ curl -X 'GET' \
		  'http://localhost:8080/api/v1/nodes' \
		  -H 'accept: application/json' \
		  -H 'Authorization: Bearer eyJ1c2VybmFtZSI6ICJjbG9jayIsICJwYXNzd29yZCI6ICJjNjQyMzU3Zi1iZGUxLTQ5YmQtYWFhYy1jNzZlMjBkNDAyY2EifQ=='
		```
		Success, if you get something like the following
		```
		{
		  "detail": "Forbidden"
		}
		```
		Failure, if you get something different
	2. Test creating a node `[POST]` `/api/v1/nodes`
		```
		$ curl -X 'POST' \
		  'http://localhost:8080/api/v1/nodes' \
		  -H 'accept: application/json' \
		  -H 'Authorization: Bearer eyJ1c2VybmFtZSI6ICJjbG9jayIsICJwYXNzd29yZCI6ICJjNjQyMzU3Zi1iZGUxLTQ5YmQtYWFhYy1jNzZlMjBkNDAyY2EifQ==' \
		  -H 'Content-Type: application/json' \
		  -d '{
		  "type": "opennebula",
		  "hostname": "str1ng",
		  "ipaddr": "192.168.0.1",
		  "comment": "string",
		  "flavour": "small"
		}'
		```
		Success, if you get something like the following
		```
		{
		  "detail": "Forbidden"
		}
		```
		Failure, if you get something different
	3. Testing retrieving a node `[GET]` `/api/v1/nodes/1`
		```
		$ curl -X 'GET' \
		  'http://localhost:8080/api/v1/nodes/1' \
		  -H 'accept: application/json' \
		  -H 'Authorization: Bearer eyJ1c2VybmFtZSI6ICJjbG9jayIsICJwYXNzd29yZCI6ICJjNjQyMzU3Zi1iZGUxLTQ5YmQtYWFhYy1jNzZlMjBkNDAyY2EifQ=='
		```
		Success, if you get something like the following
		```
		{
		  "detail": "Forbidden"
		}
		```
		Failure, if you get something different
	4. Testing deleting a node `[DELETE]` `/api/v1/nodes/1`
		```
		$ curl -X 'DELETE' \
		  'http://localhost:8080/api/v1/nodes/1' \
		  -H 'accept: application/json' \
		  -H 'Authorization: Bearer eyJ1c2VybmFtZSI6ICJjbG9jayIsICJwYXNzd29yZCI6ICJjNjQyMzU3Zi1iZGUxLTQ5YmQtYWFhYy1jNzZlMjBkNDAyY2EifQ=='
		```
		Success, if you get something like the following
		```
		{
		  "detail": "Forbidden"
		}
		```
		Failure, if you get something different
3. Similarly, test the sessions endpoint, tenants endpoint and chassis endpoint.

**Comment by nphilipp** [comment]
As discussed, I rebased your changes on top of PR #152. However, this still uses the oauth2 token security which requires creating a token using the tenant name and API key, which is an unnecessary step for API users.

I took my own swing at it using HTTP Basic auth in the `dev--auth-endpoints` branch of my fork: https://github.com/nphilipp/duffy/tree/dev--auth-endpoints

It's also based on my PR #152, adding two commits on top:

- introducing the `req_tenant` FastAPI dependency which can be used in controller functions, but skips the authentication details and directly yields the authenticated tenant object instead
- adding a couple of fixtures which allow authenticating as a normal tenant, as an admin, or not at all
- use that to tighten down what users can and can't do in the API

Please give it a look.

**Comment by gridhead** [comment]
To follow up on https://github.com/CentOS/duffy/pull/156#issuecomment-999060789, the PR does make of Oauth2 token security and creation of a token can be considered as a one-time self-service step for the clients. We will put the Swagger UI docs into user in order to make this happen. Allow me to explain how.

1. For a newly created tenant, they would have have a set of information related to their tenant account - of which, the `tenant.name` (we'll call it `username` in this context) and `tenant.api_key` (unencrypted) (we'll call it `password` in this context) are the ones that we'd note.

2. We will now ask the tenant to open up a browser and head to `https://<whereverduffygetsdeployed>.centos.org/docs`. They will get to see the following page.
	image

3. The tenants will now scroll down to the **Token** section and expand the `/api/v1/token` to _Obtain Authentication Token_ as stated in the section header. They will get to see the following page.
	image

4. The tenants will then click on **Try it out** button and enter their username and password (`tenant.name` and `tenant.api_key` (unencrypted) respectively) here in the `username` and `password` fields. Every other field are to be left blank. The following is an example of how it would look like when they would do it.
	image

5. On clicking on the **Execute** button, the provided `username` and `password` combination would be checked against those stored in the database and on successful authentication, they would be responded with a JSON having `access_token` and `token_type`. The tenants are supposed to keep a note of the same and use this in their automated scripts. The following is an example of how it would look like when they would do it.
	image

As the token is not dependent on time and hence, will not expire or change. The clients have to do this just one time and they can retrieve the `access_token` again, should they lose it as long as they have the `tenant.name` and `tenant.api_key` (unencrypted). 

This is my justification to why we would want to stick with this implementation. That being said, I will take a look at yours shortly. :)

**Comment by gridhead** [comment]
https://github.com/CentOS/duffy/pull/159 does what this PR was supposed to. Closing this PR.

**Pull request closed without merging**
